import TanstackProvider from "@/providers/TanstackProvider";
import { Provider } from "@/components/ui/provider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <TanstackProvider>
          <Provider>{children}</Provider>
        </TanstackProvider>
      </body>
    </html>
  );
}
